build_from:
  aarch64: ghcr.io/hassio-addons/debian-base:9.3.0
  amd64: ghcr.io/hassio-addons/debian-base:9.3.0
labels:
  org.opencontainers.image.title: Scanner Server
  org.opencontainers.image.description: Share a USB scanner over the network with AirScan/eSCL
  org.opencontainers.image.source: https://github.com/Potochi/homeassistant-addons
  org.opencontainers.image.licenses: GPL-3.0-or-later
